# --------------------------------- Vars ---------------------------------------
XDG_CONFIG_HOME=${HOME}/.config
XDG_CACHE_HOME=${HOME}/.cache
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state

EDITOR=nvim
VISUAL=nvim
PAGER=less

# --------------------------------- Paths --------------------------------------

# Prepend user local binaries (where your tmux-sessionizer lives)
export PATH="$HOME/.local/bin:$PATH"

# Go/Rust/Node specific paths if you use them
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/share/go/bin:$PATH"
