; Colorscheme
; include-file = ${env:POLYBAR_COLLECTION}/colorscheme/gruvbox.ini

; Theme
; include-directory = ${env:POLYBAR_COLLECTION}/themes/murz

[colors]
bg0 = #282828
bg1 = #3c3836
fg0 = #fbf1c7
fg1 = #ebdbb2

red0 = #fb4934
red1 = #cc241d
green0 = #b8bb26
green1 = #98971a
yellow0 = #fabd2f
yellow1 = #d79921
blue0 = #83a598
blue1 = #458588
purple0 = #d3869b
purple1 = #b16286
aqua0 = #8ec07c
aqua1 = #689d6a

semi-trans = #ee282828
full-trans = #00282828

[bar/main]
width = 100%
height = 30

bottom = false
fixed-center = true

offset-x = 0
offset-y = 0

background = ${colors.semi-trans}
foreground = ${colors.fg0}

; Options: bspwm, i3
; wm-restack = i3
; wm-restack = awesome
modules-center = test-text
modules-right = taskwarrior

; icons normal size
font-0 = "RobotoMono Nerd Font:style=Normal:size=11;3"
; icons big size (most for border)
font-1 = "RobotoMono Nerd Font:style=Normal:size=19;5"
; text normal
font-2 = "RobotoMono Nerd Font:style=Normal:size=9;3"
; text medium
font-3 = "RobotoMono Nerd Font:style=Medium:size=9;3"
; text italic
font-4 = "RobotoMono Nerd Font:style=Italic:size=9;3"
; text bold
font-5 = "RobotoMono Nerd Font:style=Bold:size=9;3"
; material icons
font-6 = "Material Icons:size=11;4"

[module/test-text]
type = custom/text
content = "Polybar is working!"

[module/taskwarrior]
type = custom/script
exec = task _get 1.description
interval = 10
