;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
; workspaces | tasks | tray
;
;==========================================================
; 
; Docs:
;   Each section is defined by square brackets: [bar/mybar] or [module/cpu] for example
;   Each section then has key-value pairs within it.
;
; Module formatting:
;   - modules-center, modules-left, and modules-right define the positioning of contents


[colors]
background = #1C1A18
borders = #E8E1D4
personal = #BC7101
development = #637252
work = #3F566F
misc = #5A3E5B
overdue = #7A2F2F
inactive = #575757
transparent = #00000000

[bar/base]
dpi = ${xrdb:Xft.dpi:-1}
height = 24pt
; offset-y = 5pt
radius = 8
; open polybar socket to interact with it
enable-ipc = true
; background = ${colors.background}
background = ${colors.background}
foreground = ${colors.borders}
border-size = 1pt
line-size = 2pt
border-color = ${colors.borders}
font-0 = "RobotoMono Nerd Font Mono:style=Normal:size=11;3"
font-1 = "RobotoMono Nerd Font Mono:style=Normal:size=19;5"
font-2 = "RobotoMono Nerd Font Mono:style=Normal:size=9;3"
font-3 = "RobotoMono Nerd Font Mono:style=Medium:size=9;3"
font-4 = "RobotoMono Nerd Font Mono:style=Italic:size=9;3"
font-5 = "RobotoMono Nerd Font Mono:style=Bold:size=9;3"
font-6 = "Material Icons:size=11;4"

[bar/left]
inherit = bar/base
; 9 workspaces, 1 character each. 1 padding on either side - 27 total characters
; border = 2pt left and right so total width = 27chr + 4pt
width = 226pt
; offset-x = 5pt
modules-left =  workspaces

[bar/center]
inherit = bar/base
width = 620pt
; offset-x = 50%:-115pt
offset-x = 50%:-310pt
modules-center = custom-taskwarrior 

[bar/right]
inherit = bar/base
width = 200pt
; offset-x = 100%:-305pt
offset-x = 100%:-200pt
; modules-center = vpn eth wlan pulseaudio battery date
modules-right = systray battery date
; This adds spaces between each module in this specific bar
module-margin = 1
; padding-right = 1

;--------------------------------- Modules -------------------------------------

[module/workspaces]
type = internal/xworkspaces
; Provide clicking functionality
enable-click = true

; --- ACTIVE WORKSPACE ---
; The %name% token outputs the name of the workspace
label-active = %name%
label-active-font = 2
; Use the accent color we defined earlier for the active workspace
label-active-foreground = ${colors.borders}
label-active-background = ${colors.inactive}
; label-active-underline = ${colors.borders}
label-active-underline = #ff0000
; label-active-padding-left = 1
; label-active-padding-right = 1
label-active-padding = 1

; --- OCCUPIED WORKSPACE ---
label-occupied = %name%
label-occupied-font = 2
label-occupied-foreground = ${colors.inactive}
label-occupied-padding = 1

; --- EMPTY WORKSPACE ---
; Many people make empty workspaces slightly transparent or dim
label-empty = %name%
label-empty-font = 2
label-empty-foreground = #555555
label-empty-padding = 1

[module/custom-taskwarrior]
; 1. Change the type from custom/text to custom/script
type = custom/script
; 2. Point to the python script we created
exec = python3 ~/.config/polybar/scripts/task_renderer.py 79
; 3. Set how often it should refresh (in seconds)
interval = 5
; 4. Keep your formatting
label-foreground = ${colors.borders}

[module/battery]
type = internal/battery
full-at = 99
low-at = 15
; 5 second interval default - changed to 30
poll-interval = 30

; IMPORTANT: You must verify your battery and adapter names.
; Run: ls -1 /sys/class/power_supply/ in your terminal.
battery = BAT0
adapter = ADP1

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = "󰁹 100%"
label-low = "󰂃 %percentage%%"

; Discharging battery icons
ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰁺
ramp-capacity-2 = 󰁾
ramp-capacity-3 = 󰂂
ramp-capacity-4 = 󰁹

; Charging animation icons
animation-charging-0 = 󰢟
animation-charging-1 = 󰂆
animation-charging-2 = 󰂉
animation-charging-3 = 󰂋
animation-charging-4 = 󰂄
animation-charging-framerate = 750

[module/date]
type = internal/date
interval = 1

date = %H:%M
; Clicking the module will toggle to this detailed format
; date-alt = %Y-%m-%d %H:%M:%S
date-alt = %a %d/%m

label = "%date%"
label-foreground = ${colors.borders}
label-padding = 1


[module/systray]
type = internal/tray
tray-spacing = 8pt


