#!/usr/bin/env bash

# Need stow and awesome
check_deps stow awesome || return 1

# stow the picom configuration for awesomewm
system_stow picom

system_stow polybar

if [[ $DRY_RUN -eq 0 ]]; then
    if [[ "$SHELL" != *"zsh"* ]] && command -v zsh &>/dev/null; then
        log_info "Changing default shell to ZSH..."
        chsh -s "$(command -v zsh)"
    fi
fi

log_pass "Core configuration complete."


setup_awesome_config() {
    local download_dir="$HOME/.config"
    local target_dir="$download_dir/awesome"
    local repo_url="git@github.com:Jelso13/awesome.git"

    mkdir --parents "$download_dir"

    if [[ -d "$target_dir/.git" ]]; then
        log_info "Awesomewm config already exists. Pulling latest changes..."
        # Use -C to run git inside the target directory without 'cd'-ing
        git -C "$target_dir" pull
    else
        log_info "Cloning Awesomewm config..."
        git clone "$repo_url" "$target_dir"
    fi
}

setup_awesome_config


