#!/usr/bin/env bash

assert_command nvim

setup_nvim_config() {
    local download_dir="$HOME/.config"
    local target_dir="$download_dir/nvim"
    local repo_url="git@github.com:Jelso13/nvim.git"

    mkdir --parents "$download_dir"

    if [[ -d "$target_dir/.git" ]]; then
        log_info "Neovim config already exists. Pulling latest changes..."
        # Use -C to run git inside the target directory without 'cd'-ing
        git -C "$target_dir" pull
    else
        log_info "Cloning Neovim config..."
        git clone "$repo_url" "$target_dir"
    fi
}

setup_nvim_config
